<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <Optimize>false</Optimize>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>MyLittleRangeBook.Tests</_Parameter1>
        </AssemblyAttribute>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="ByteAether.Ulid" Version="1.4.0" />
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="dbup-core" Version="6.1.1" />
        <PackageReference Include="dbup-sqlite" Version="6.0.4" />
        <PackageReference Include="Fisher" Version="1.0.5" />
        <PackageReference Include="FluentResults" Version="4.0.0" />
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SerilogTraceListener" Version="3.2.0" />
        <PackageReference Include="Spectre.Console" Version="0.57.2" />
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
        <PackageReference Include="WolverineFx" Version="6.31.0" />

    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Config\AppSettings\*.json" />
        <EmbeddedResource Include="Persistence\Sqlite\Scripts\*.sql" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyLittleRangeBook.FIT\MyLittleRangeBook.FIT.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\data\sample-fit-files\01-16-2026_11-29-31.fit">
        <Link>data\sample-fit-files\01-16-2026_11-29-31.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\01-16-2026_11-42-39.fit">
        <Link>data\sample-fit-files\01-16-2026_11-42-39.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\01-16-2026_11-53-46.fit">
        <Link>data\sample-fit-files\01-16-2026_11-53-46.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\01-16-2026_12-13-09.fit">
        <Link>data\sample-fit-files\01-16-2026_12-13-09.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\03-06-2026_14-11-13.fit">
        <Link>data\sample-fit-files\03-06-2026_14-11-13.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\03-06-2026_14-42-52.fit">
        <Link>data\sample-fit-files\03-06-2026_14-42-52.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\04-16-2026_13-11-21.fit">
        <Link>data\sample-fit-files\04-16-2026_13-11-21.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\04-16-2026_13-21-49.fit">
        <Link>data\sample-fit-files\04-16-2026_13-21-49.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\04-21-2026_15-36-07.fit">
        <Link>data\sample-fit-files\04-21-2026_15-36-07.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\04-21-2026_15-42-04.fit">
        <Link>data\sample-fit-files\04-21-2026_15-42-04.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\04-21-2026_15-53-03.fit">
        <Link>data\sample-fit-files\04-21-2026_15-53-03.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\04-21-2026_16-09-58.fit">
        <Link>data\sample-fit-files\04-21-2026_16-09-58.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\05-05-2026_14-45-28.fit">
        <Link>data\sample-fit-files\05-05-2026_14-45-28.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\05-05-2026_15-14-49.fit">
        <Link>data\sample-fit-files\05-05-2026_15-14-49.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\11-29-2025_13-41-40.fit">
        <Link>data\sample-fit-files\11-29-2025_13-41-40.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\11-29-2025_13-56-08.fit">
        <Link>data\sample-fit-files\11-29-2025_13-56-08.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\11-30-2025_12-38-41.fit">
        <Link>data\sample-fit-files\11-30-2025_12-38-41.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\12-31-2025_11-39-01.fit">
        <Link>data\sample-fit-files\12-31-2025_11-39-01.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-fit-files\12-31-2025_12-19-19.fit">
        <Link>data\sample-fit-files\12-31-2025_12-19-19.fit</Link>
      </Content>
      <Content Include="..\..\..\data\sample-images\BX_RAW_PHOTO_1590715558170.jpg">
        <Link>data\sample-images\BX_RAW_PHOTO_1590715558170.jpg</Link>
      </Content>
      <Content Include="..\..\..\data\sample-images\M3-Carl-Gustav.jpg">
        <Link>data\sample-images\M3-Carl-Gustav.jpg</Link>
      </Content>
      <Content Include="..\..\..\data\sample-shotview-csv-files\CZ457_2026-07-05_13-30-54.csv">
        <Link>data\sample-shotview-csv-files\CZ457_2026-07-05_13-30-54.csv</Link>
      </Content>
      <Content Include="..\..\..\data\sample-shotview-csv-files\Phoenix_Indoor_range_2026-05-05_14-45-28.csv">
        <Link>data\sample-shotview-csv-files\Phoenix_Indoor_range_2026-05-05_14-45-28.csv</Link>
      </Content>
      <Content Include="..\..\..\data\sample-shotview-csv-files\Phoenix_Indoor_range_2026-05-05_15-14-49.csv">
        <Link>data\sample-shotview-csv-files\Phoenix_Indoor_range_2026-05-05_15-14-49.csv</Link>
      </Content>
      <Content Include="..\..\..\data\simple_range_events.csv">
        <Link>data\simple_range_events.csv</Link>
      </Content>
    </ItemGroup>

</Project>
