<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.3" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="XUnit.v3" Version="4.0.1" />
        <PackageReference Include="Avalonia.Headless.XUnit" Version="12.1.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedControls\SharedControls.csproj" />
    </ItemGroup>
</Project>
