DROP INDEX IF EXISTS Firearms_Id_IDX;
DROP INDEX IF EXISTS IX_Firearms_Id;
DROP INDEX IF EXISTS Firearms_Name_IDX;
DROP INDEX IF EXISTS IX_Firearms_Name;
DROP INDEX IF EXISTS FitFiles_Id_IDX;
DROP INDEX IF EXISTS FitFiles_FileName_IDX;
DROP INDEX IF EXISTS IX_FitFiles_Filename;
DROP INDEX IF EXISTS IX_Firearms_Id;
DROP INDEX IF EXISTS FitFiles_Id_IDX;
DROP INDEX IF EXISTS IX_FitFiles_Id;
DROP INDEX IF EXISTS FitFiles_FileName_IDX;
DROP INDEX IF EXISTS IX_FitFiles_Filename;
DROP INDEX IF EXISTS IX_FitFiles_Modified;
DROP INDEX IF EXISTS SimpleRangeEvents_Id_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Id;
DROP INDEX IF EXISTS SimpleRangeEvents_EventDate_FirearmName_RangeName_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_EventDate_FirearmName_RangeName;
DROP INDEX IF EXISTS SimpleRangeEvents_Firearm_Date_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Firearm_Date;
DROP INDEX IF EXISTS SimpleRangeEvents_Modified_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Modified;
DROP INDEX IF EXISTS SimpleRangeEvents_Range_Date_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Range_Date;
DROP INDEX IF EXISTS IX_FitFiles_Modified;
DROP INDEX IF EXISTS SimpleRangeEvents_Id_IDX;
DROP INDEX IF Exists IX_SimpleRangeEvents_Id;
DROP INDEX IF EXISTS SimpleRangeEvents_EventDate_FirearmName_RangeName_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_EventDate_FirearmName_RangeName;
DROP INDEX IF EXISTS SimpleRangeEvents_Firearm_Date_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Firearm_Date;
DROP INDEX IF EXISTS SimpleRangeEvents_Modified_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Modified;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Modified_index;
DROP INDEX IF EXISTS SimpleRangeEvents_Range_Date_IDX;
DROP INDEX IF EXISTS IX_SimpleRangeEvents_Range_Date;

CREATE UNIQUE INDEX IX_Firearms_Id ON Firearms (Id);
CREATE UNIQUE INDEX IX_Firearms_Name ON Firearms (Name);
CREATE UNIQUE INDEX IX_FitFiles_Id ON FitFiles (Id);
CREATE UNIQUE INDEX IX_FitFiles_Filename ON FitFiles (FileName);
CREATE INDEX IX_FitFiles_Modified ON FitFiles (Modified);
CREATE UNIQUE INDEX IX_SimpleRangeEvents_Id ON SimpleRangeEvents (Id);
CREATE INDEX IX_SimpleRangeEvents_EventDate_FirearmName_RangeName ON SimpleRangeEvents (EventDate, FirearmName, RangeName);
CREATE INDEX IX_SimpleRangeEvents_Firearm_Date ON SimpleRangeEvents (FirearmName, EventDate);
CREATE INDEX IX_SimpleRangeEvents_Modified ON SimpleRangeEvents (Modified);
CREATE INDEX IX_SimpleRangeEvents_Range_Date ON SimpleRangeEvents (RangeName, EventDate);

