using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using ByteAether.Ulid;

namespace MyLittleRangeBook.Models
{
    /// <summary>
    ///     Records in the database have a unique string ID value, and also the Serialized ID generated by the database.
    /// </summary>
    /// <param name="Id">A unique string that is the primary identifier of the entity. Either a Nanoid or a ULID.</param>
    /// <param name="RowId">A long that is generated by the database when the entity is created.</param>
    public readonly record struct EntityId(string Id, long? RowId);

    /// <summary>
    ///     This is a unique ID value that is sortable by time.
    /// </summary>
    public readonly record struct MlrbId
    {
        static readonly Ulid.GenerationOptions DefaultOptions = new()
        {
            Monotonicity = Ulid.GenerationOptions.MonotonicityOptions.MonotonicIncrement
        };

        public static readonly MlrbId Empty = new(Ulid.Empty);

        readonly Ulid _id;

        MlrbId(Ulid id)
        {
            _id = id;
        }

        public MlrbId() : this(DateTimeOffset.UtcNow)
        {
        }


        public MlrbId(DateTimeOffset dto)
        {
            _id = Ulid.New(dto, DefaultOptions);
        }

        public DateTime DateTimeLocal => _id.Time.ToLocalTime().DateTime;

        public DateTimeOffset DateTimeOffset => _id.Time;


        /// <summary>
        ///     THe FIT file name should be the local date & time of when it was created. DateTimeKind will be local.
        /// </summary>
        /// <param name="fitFileName"></param>
        /// <returns></returns>
        public static MlrbId FromFitFileName(string fitFileName)
        {
            string withoutExtension = Path.GetFileNameWithoutExtension(fitFileName);

            const string FORMAT = "MM-dd-yyyy_HH-mm-ss";

            var timestamp = DateTime.ParseExact(
                withoutExtension,
                FORMAT,
                CultureInfo.InvariantCulture,
                DateTimeStyles.AssumeLocal // ensures Kind == Local
            );

            return From(timestamp);
        }

        public static MlrbId From(EntityId eid)
        {
            return new MlrbId(FromString(eid.Id));
        }

        /// <summary>
        ///     Creates a new <see cref="MlrbId" /> instance based on a given <see cref="DateOnly" /> value.
        /// </summary>
        /// <param name="dateOnly">
        ///     The <see cref="DateOnly" /> value for which a new <see cref="MlrbId" /> instance will be generated.
        ///     The ID will include the current time portion from the system clock.
        /// </param>
        /// <returns>
        ///     A new <see cref="MlrbId" /> instance generated using the specified date and the current time from the system clock.
        /// </returns>
        public static MlrbId From(DateOnly dateOnly)
        {
            if (dateOnly == default)
            {
                return new MlrbId();
            }

            // [TO20260516] We're assuming that the dateOnly is in the current timezone.  We will make
            // a DateTimeOffset by combining the DateOnly with the time right now.
            TimeZoneInfo zone = TimeZoneInfo.Local;
            var now = TimeOnly.FromDateTime(DateTime.Now);
            var dt = dateOnly.ToDateTime(now);
            TimeSpan offset = zone.GetUtcOffset(dt);
            DateTimeOffset dto = new(dt, offset);

            return new MlrbId(dto);
        }

        /// <summary>
        ///     Creates an instance of <see cref="MlrbId" /> from the specified <see cref="DateTime" />.
        /// </summary>
        /// <param name="dateTime">
        ///     The <see cref="DateTime" /> value to create the MlrbId from. The kind of DateTime (Utc, Local,
        ///     or Unspecified) determines how the value is processed.
        /// </param>
        /// <returns>A new instance of <see cref="MlrbId" /> corresponding to the provided <see cref="DateTime" />.</returns>
        /// <exception cref="InvalidOperationException">Thrown when the <see cref="DateTime.Kind" /> is an unexpected value.</exception>
        public static MlrbId From(DateTime dateTime)
        {
            // [TO20260516] Perhaps overly explicity, but assume any .Unspecified is local time.
            DateTimeOffset dto = dateTime.Kind switch
            {
                DateTimeKind.Utc => new DateTimeOffset(dateTime, TimeSpan.Zero),
                DateTimeKind.Local => new DateTimeOffset(dateTime, TimeZoneInfo.Local.GetUtcOffset(dateTime)),
                DateTimeKind.Unspecified => new DateTimeOffset(dateTime, TimeZoneInfo.Local.GetUtcOffset(dateTime)),
                _ => throw new InvalidOperationException($"Unexpected DateTimeKind: {dateTime.Kind}")
            };

            return new MlrbId(dto);
        }

        public static MlrbId FromString(string stringValue)
        {
            if (string.IsNullOrWhiteSpace(stringValue))
            {
                return Empty;
            }

            Ulid ulid;
            if (Ulid.IsValid(stringValue))
            {
                ulid = Ulid.Parse(stringValue);
            }
            else
            {
                // We need a deterministic 16-byte value for the Ulid.
                // A SHA256 hash of the string is a reliable way to get this.
                byte[] hash = SHA256.HashData(Encoding.UTF8.GetBytes(stringValue));
                ulid = Ulid.New(hash.AsSpan(0, 16).ToArray());
            }

            return new MlrbId(ulid);
        }

        public static implicit operator EntityId(MlrbId d)
        {
            return new EntityId(d._id.ToString(), null);
        }

        public static implicit operator string(MlrbId d)
        {
            return d._id.ToString();
        }

        public static implicit operator byte[](MlrbId d)
        {
            return d._id.ToByteArray();
        }

        public static implicit operator Ulid(MlrbId d)
        {
            return d._id;
        }

        public override string ToString()
        {
            return _id.ToString();
        }

        public byte[] ToByteArray()
        {
            return _id.ToByteArray();
        }
    }
}
