using System.Security.Cryptography;
using System.Text;
using ByteAether.Ulid;

namespace MyLittleRangeBook.Models
{
    /// <summary>
    ///     Records in the database have a unique string ID value, and also the Serialized ID generated by the database.
    /// </summary>
    /// <param name="Id">A unique string that is the primary identifier of the entity. Either a Nanoid or a ULID.</param>
    /// <param name="RowId">A long that is generated by the database when the entity is created.</param>
    public record EntityId(string Id, long? RowId);

    /// <summary>
    ///     This is a unique ID value that is sortable by time.
    /// </summary>
    public record MlrbId
    {
        internal static readonly Ulid.GenerationOptions DefaultOptions = new()
        {
            Monotonicity = Ulid.GenerationOptions.MonotonicityOptions.MonotonicIncrement
        };

        public static readonly MlrbId Empty = new(Ulid.Empty);

        readonly Ulid _id;

        MlrbId(Ulid id)
        {
            _id = id;
        }

        public MlrbId() : this(DateTimeOffset.UtcNow)
        {
        }

        public MlrbId(DateTimeOffset dto)
        {
            _id = Ulid.New(dto, DefaultOptions);
        }

        public static MlrbId From(EntityId eid)
        {
            return new MlrbId(FromString(eid.Id));
        }

        public static MlrbId FromString(string nanoid)
        {
            if (string.IsNullOrWhiteSpace(nanoid))
            {
                return Empty;
            }

            Ulid ulid;
            if (Ulid.IsValid(nanoid))
            {
                ulid = Ulid.Parse(nanoid);
            }
            else
            {
                // We need a deterministic 16-byte value for the Ulid.
                // A SHA256 hash of the Nanoid string is a reliable way to get this.
                byte[] hash = SHA256.HashData(Encoding.UTF8.GetBytes(nanoid));
                ulid = Ulid.New(hash.AsSpan(0, 16).ToArray());
            }

            return new MlrbId(ulid);
        }


        public static implicit operator EntityId(MlrbId d)
        {
            return new EntityId(d._id.ToString(), null);
        }

        public static implicit operator string(MlrbId d)
        {
            return d._id.ToString();
        }

        public static implicit operator byte[](MlrbId d)
        {
            return d._id.ToByteArray();
        }

        public static implicit operator Ulid(MlrbId d)
        {
            return d._id;
        }

        public override string ToString()
        {
            return _id.ToString();
        }

        public byte[] ToByteArray()
        {
            return _id.ToByteArray();
        }
    }
}
