using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using ByteAether.Ulid;

namespace MyLittleRangeBook.Models
{
    /// <summary>
    ///     Records in the database have a unique string ID value, and also the Serialized ID generated by the database.
    /// </summary>
    /// <param name="Id">A unique string that is the primary identifier of the entity. Either a Nanoid or a ULID.</param>
    /// <param name="RowId">A long that is generated by the database when the entity is created.</param>
    public readonly record struct EntityId(string Id, long? RowId);

    /// <summary>
    ///     This is a unique ID value that is sortable by time.
    /// </summary>
    public readonly record struct MlrbId
    {
        internal static readonly Ulid.GenerationOptions DefaultOptions = new()
        {
            Monotonicity = Ulid.GenerationOptions.MonotonicityOptions.MonotonicIncrement
        };

        public static readonly MlrbId Empty = new(Ulid.Empty);

        readonly Ulid _id;

        internal MlrbId(Ulid id)
        {
            _id = id;
        }

        public MlrbId() : this(DateTimeOffset.UtcNow)
        {
        }

        public MlrbId(DateTimeOffset dto)
        {
            _id = Ulid.New(dto, DefaultOptions);
        }

        public DateTime DateTimeLocal => _id.Time.ToLocalTime().DateTime;

        public DateTimeOffset DateTimeOffset => _id.Time;

        /// <summary>
        ///     Creates a new <see cref="Ulid" /> that is sortable by timestamp and incorporates a deterministic hash of a given
        ///     filename.
        /// </summary>
        /// <param name="filename">
        ///     The name of the file, which will be hashed for deterministic randomness in the ULID generation.
        ///     This value must not be null, empty, or consist solely of whitespace.
        /// </param>
        /// <param name="timestamp">
        ///     The point in time that will be used as the basis for the timestamp portion of the ULID.
        ///     This ensures that the generated ULID is chronologically sortable.
        /// </param>
        /// <returns>
        ///     A new <see cref="Ulid" /> instance that contains a timestamp generated from the provided
        ///     <paramref name="timestamp" />
        ///     and a deterministic randomness derived from the hashed <paramref name="filename" />.
        /// </returns>
        /// <exception cref="ArgumentException">
        ///     Thrown when <paramref name="filename" /> is null, empty, or contains only whitespace characters.
        /// </exception>
        static Ulid CreateFileUlid(string filename, DateTimeOffset timestamp)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(filename);

            // The timestamp (first 48 bits) ensures chronological sortability
            // Hash the filename to get deterministic randomness (remaining 80 bits)
            byte[] hash = SHA256.HashData(Encoding.UTF8.GetBytes(filename));
            Span<byte> randomness = stackalloc byte[10];
            hash[..10].CopyTo(randomness);

            // ULID struct: [48-bit timestamp][80-bit randomness]
            // Sorting is by timestamp first, then randomness
            return Ulid.New(timestamp, randomness);
        }

        /// <summary>
        ///     Creates a new <see cref="MlrbId" /> instance from an existing <see cref="EntityId" />.
        /// </summary>
        /// <param name="eid">
        ///     The <see cref="EntityId" /> containing a unique string identifier from which the <see cref="MlrbId" /> will be
        ///     derived.
        ///     The string ID in <paramref name="eid" /> must represent a valid ULID.
        /// </param>
        /// <returns>
        ///     A new <see cref="MlrbId" /> instance generated from the unique string identifier in the provided
        ///     <see cref="EntityId" />.
        /// </returns>
        /// <exception cref="ArgumentException">
        ///     Thrown if the string ID in <paramref name="eid" /> is null, empty, or not a valid ULID.
        /// </exception>
        public static MlrbId From(EntityId eid)
        {
            return new MlrbId(FromString(eid.Id));
        }

        /// <summary>
        ///     Creates a new <see cref="MlrbId" /> instance based on a given <see cref="DateOnly" /> value.
        /// </summary>
        /// <param name="dateOnly">
        ///     The <see cref="DateOnly" /> value for which a new <see cref="MlrbId" /> instance will be generated.
        ///     The ID will include the current time portion from the system clock.
        /// </param>
        /// <returns>
        ///     A new <see cref="MlrbId" /> instance generated using the specified date and the current time from the system clock.
        /// </returns>
        public static MlrbId From(DateOnly dateOnly)
        {
            if (dateOnly == default)
            {
                return new MlrbId();
            }

            // [TO20260516] We're assuming that the dateOnly is in the current timezone.  We will make
            // a DateTimeOffset by combining the DateOnly with the time right now.
            TimeZoneInfo zone = TimeZoneInfo.Local;
            var now = TimeOnly.FromDateTime(DateTime.Now);
            var dt = dateOnly.ToDateTime(now);
            TimeSpan offset = zone.GetUtcOffset(dt);
            DateTimeOffset dto = new(dt, offset);

            return new MlrbId(dto);
        }

        /// <summary>
        ///     Creates an instance of <see cref="MlrbId" /> from the specified <see cref="DateTime" />.
        /// </summary>
        /// <param name="dateTime">
        ///     The <see cref="DateTime" /> value to create the MlrbId from. The kind of DateTime (Utc, Local,
        ///     or Unspecified) determines how the value is processed.
        /// </param>
        /// <returns>A new instance of <see cref="MlrbId" /> corresponding to the provided <see cref="DateTime" />.</returns>
        /// <exception cref="InvalidOperationException">Thrown when the <see cref="DateTime.Kind" /> is an unexpected value.</exception>
        public static MlrbId From(DateTime dateTime)
        {
            // [TO20260516] Perhaps overly explicity, but assume any .Unspecified is local time.
            DateTimeOffset dto = dateTime.Kind switch
            {
                DateTimeKind.Utc => new DateTimeOffset(dateTime, TimeSpan.Zero),
                DateTimeKind.Local => new DateTimeOffset(dateTime, TimeZoneInfo.Local.GetUtcOffset(dateTime)),
                DateTimeKind.Unspecified => new DateTimeOffset(dateTime, TimeZoneInfo.Local.GetUtcOffset(dateTime)),
                _ => throw new InvalidOperationException($"Unexpected DateTimeKind: {dateTime.Kind}")
            };

            return new MlrbId(dto);
        }

        /// <summary>
        ///     Create a MlrbId from a FileInfo object (based on file last write time and filename)
        /// </summary>
        /// <param name="fileInfo"></param>
        /// <returns></returns>
        public static MlrbId FromFile(FileInfo fileInfo)
        {
            if (!fileInfo.Exists)
            {
                throw new FileNotFoundException("File does not exist on disk: " + fileInfo.FullName);
            }

            var dto = new DateTimeOffset(fileInfo.LastWriteTimeUtc);
            Ulid ulid = CreateFileUlid(fileInfo.FullName, dto);

            return new MlrbId(ulid);
        }

        /// <summary>
        ///     Create a MlrbId from a FIT file, using the name of the file as the creation date.
        /// </summary>
        /// <param name="fitFileName"></param>
        /// <returns></returns>
        public static MlrbId FromFitFile(string fitFileName)
        {
            const string FIT_FILENAME_FORMAT = "MM-dd-yyyy_HH-mm-ss";
            ArgumentException.ThrowIfNullOrWhiteSpace(fitFileName);

            // [TO20260521] Ensure we handle both Windows and Linux separators when extracting the filename.
            // On Linux, Path.GetFileNameWithoutExtension does not recognize '\' as a separator.
            string normalizedPath = fitFileName.Replace('\\', '/');
            string withoutExtension = Path.GetFileNameWithoutExtension(normalizedPath);

            var localTimestamp = DateTime.ParseExact(
                withoutExtension,
                FIT_FILENAME_FORMAT,
                CultureInfo.InvariantCulture,
                DateTimeStyles.AssumeLocal // ensures Kind == Local
            );

            Ulid ulid = CreateFileUlid(fitFileName, localTimestamp);

            return new MlrbId(ulid);
        }

        /// <summary>
        ///     Converts the provided string value into an instance of <see cref="MlrbId" />.
        ///     If the string is determined to be a valid ULID, it is directly converted.
        ///     Otherwise, a deterministic ULID is generated by hashing the input string.
        /// </summary>
        /// <param name="stringValue">
        ///     The string representation to be converted into a <see cref="MlrbId" />.
        ///     This value cannot be null, empty, or consist solely of whitespace.
        /// </param>
        /// <returns>
        ///     A new <see cref="MlrbId" /> instance created from the provided <paramref name="stringValue" />.
        ///     If the input string is null, empty, or whitespace, the method returns <see cref="MlrbId.Empty" />.
        /// </returns>
        public static MlrbId FromString(string stringValue)
        {
            if (string.IsNullOrWhiteSpace(stringValue))
            {
                return Empty;
            }

            Ulid ulid;
            if (Ulid.IsValid(stringValue))
            {
                ulid = Ulid.Parse(stringValue);
            }
            else
            {
                // We need a deterministic 16-byte value for the Ulid.
                // A SHA256 hash of the string is a reliable way to get this.
                byte[] hash = SHA256.HashData(Encoding.UTF8.GetBytes(stringValue));
                ulid = Ulid.New(hash.AsSpan(0, 16).ToArray());
            }

            return new MlrbId(ulid);
        }

        public static implicit operator EntityId(MlrbId d)
        {
            return new EntityId(d._id.ToString(), null);
        }

        public static implicit operator string(MlrbId d)
        {
            return d._id.ToString();
        }

        public static implicit operator byte[](MlrbId d)
        {
            return d._id.ToByteArray();
        }

        public static implicit operator Ulid(MlrbId d)
        {
            return d._id;
        }

        public override string ToString()
        {
            return _id.ToString();
        }

        public byte[] ToByteArray()
        {
            return _id.ToByteArray();
        }
    }
}
