package fs

// LbrFiles is a collection of all the serialized CSV files that are generated by LabRadar.
type LbrFiles struct {
	InputDir string
	Files    []*CsvFile
}

func (df LbrFiles) String() string {
	return df.InputDir
}
