name: Build .NET Framework Application

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows, linux ]
    runs-on: ${{ matrix.platform == 'windows' && 'windows-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Publish single-file EXE for the CLI
        run: |
          dotnet publish src/mlrb/MyLittleRangeBook.CLI/MyLittleRangeBook.CLI.csproj -c Release \
            -r ${{ matrix.platform == 'windows' && 'win-x64' || 'linux-x64' }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -o ./out/MyLittleRangeBook-CLI
        shell: bash

      - name: Publish single-file EXE for the GUI
        run: |
          dotnet publish src/mlrb/MyLittleRangeBook.GUI/MyLittleRangeBook.GUI.csproj -c Release \
            -r ${{ matrix.platform == 'windows' && 'win-x64' || 'linux-x64' }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -o ./out/MyLittleRangeBook-GUI
        shell: bash

      - name: Upload ${{ matrix.platform }} artifacts
        if: success()
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform }}-executables
          path: |
            out/MyLittleRangeBook-GUI/
            out/MyLittleRangeBook-CLI/
